apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app-deployment
  namespace: poligon
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 1
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: login-v2
          image: 'mcovglobal.azurecr.io/mcov-pl/devops/php-login-site:latest'
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: acr-secret