apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: poligon
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  minReadySeconds: 10
  strategy: 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80