apiVersion: v1
kind: Pod
metadata:
  name: php-login-site
  labels:
    app: login
  namespace: poligon
spec:
  containers:
    - name: login
      image: 'mcovglobal.azurecr.io/mcov-pl/devops/php-login-site:latest'
      ports:
        - containerPort: 80
  imagePullSecrets:
  - name: acr-secret
