 {{- range .Values.users }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: default
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: global-deployment
  namespace: default