clusterRoles:
- name: administrator
  rules:
    - apiGroups:
      - "*"
      resources:
      - "*"
      verbs:
      - "*"
- name: user
  rules:
    - apiGroups:
      - "*"
      resources:
      - "namespaces"
      verbs:
      - "get"
      - "list"
      - "watch"
- name: monitoring-software
  rules:
    - apiGroups:
      - "*"
      resources:
      - pods
      - nodes
      - deployments
      - apiservices
      - componentstatuses
      - namespaces
      verbs:
      - get
      - list
      - watch