apiVersion: v1
kind: PersistentVolume
metadata:
   name: kasten-backup-pvc
spec:
   capacity:
      storage: 65Gi
   volumeMode: Filesystem
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   storageClassName: nfs
   mountOptions:
      - hard
      - nfsvers=4.1
   nfs:
      path: /data
      server: 10.6.10.75