apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: kasten-backup-pvc
   namespace: kasten-io
spec:
   storageClassName: nfs
   accessModes:
      - ReadWriteMany
   resources:
      requests:
         storage: 65Gi